export const postAction = {
  GET: "GET",
  REMOVE: "REMOVE",
  GET_POST: "GET_POST",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_SUCCESS: "SET_IS_SUCCESS",
  SET_IS_ERROR: "SET_IS_ERROR",
  EDIT_POST: "EDIT_POST",
};
